# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  pull_request:
    branches: [main, master]

name: lint-changed-files

jobs:
  lint-changed-files:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::gh
            any::lintr
            any::purrr
          needs: check

      - name: Add lintr options
        run: |
          cat('\noptions(lintr.linter_file = ".lintr")\n', file = "~/.Rprofile", append = TRUE)
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Extract and lint files changed by this PR
        run: |
          files <- gh::gh("GET https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/files")
          changed_files <- purrr::map_chr(files, "filename")
          all_files <- list.files(recursive = TRUE)
          exclusions_list <- setdiff(all_files, changed_files)
          exclusions_list <- c(exclusions_list, unname(as.list(fs::dir_ls("vignettes"))), unname(as.list(fs::dir_ls("tests/fixtures"))))
          lintr::lint_package(exclusions = as.list(unique(exclusions_list)))
        shell: Rscript {0}
        env:
          LINTR_ERROR_ON_LINT: true
